import { ArrowRight, FileSearch, FileText, Globe2, Layers, Radio, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { DISCLAIMER } from '../lib/evidence';

const stages = [
  { title: 'Report', Icon: FileText, subtitle: 'A citizen lead, preserved as an observation.', text: 'A person submits a public URL, symptom, reported region, and optional context. There is no login requirement. Leads are unverified, and the reported location is not proof of where a probe ran.' },
  { title: 'Verify', Icon: Radio, subtitle: 'Technical checks from distinct vantage points.', text: 'The worker makes repeated URL checks through configured domestic and international egress routes. Operators must verify their routes’ actual countries and ISPs. Responses, timings, errors, and known blocking strings remain visible in the dossier.' },
  { title: 'Corroborate', Icon: Globe2, subtitle: 'Compare signals, keep the uncertainty.', text: 'A domestic 451 or legal-block string, alongside HTTP 200 from both foreign control countries, supports a sampled regional restriction classification. Mixed or flaky samples, generic 403 responses, and transport errors remain inconclusive.' },
  { title: 'Legal RAG Grounding', Icon: FileSearch, subtitle: 'Relevant sources, with explicit scope limits.', text: 'A local FAISS index retrieves curated statutory and judicial summaries. The current implementation uses lexical vectors and a deterministic research renderer, not an external LLM. Indian source snapshots and ECHR comparative context carry links and applicability limits.' },
  { title: 'Evidence Dossier', Icon: Layers, subtitle: 'Facts and interpretation, kept separate.', text: 'The dossier combines raw telemetry, procedural indicators, and source-grounded questions. Unknown indicators stay unknown. JSON export preserves the data; Print to PDF creates a readable record with simulation labels and the research disclaimer.' },
];

export default function About() {
  return <div className="mx-auto max-w-5xl"><p className="eyebrow mb-3">Methodology / The standard of evidence</p><h1 className="page-title">From a lead to a record.</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted">A restriction deserves scrutiny. That starts with separating what we can observe from what still needs to be established.</p>
    <div className="my-9 flex flex-wrap items-center gap-x-3 gap-y-2 border-y border-line py-5 font-mono text-xs text-signal" aria-label="Five-stage evidence pipeline">{stages.map((stage, index) => <span className="inline-flex items-center gap-3" key={stage.title}>{index > 0 && <ArrowRight size={14} className="text-muted" />}{stage.title}</span>)}</div>
    <div className="space-y-4">{stages.map(({ title, subtitle, text, Icon }, index) => <section className="panel flex flex-col gap-5 p-6 sm:flex-row sm:gap-7 sm:p-8" key={title}><span className="font-mono text-3xl text-signal/70">{String(index + 1).padStart(2, '0')}</span><div className="min-w-0 flex-1"><h2 className="flex items-center gap-3 text-xl font-semibold"><Icon size={21} className="text-signal" />{title}</h2><p className="mb-3 mt-2 text-sm font-medium text-slate-200">{subtitle}</p><p className="text-base leading-relaxed text-muted">{text}</p></div></section>)}</div>
    <section className="my-9 grid gap-7 border-y border-line py-8 md:grid-cols-2"><div><h2 className="mb-3 text-lg font-semibold">Simulation is never evidence.</h2><p className="text-sm leading-relaxed text-muted">When no live vantage configuration exists, the worker uses explicit MockFixture samples and does not contact the target. Every simulated report is labeled and excluded from confirmed-block and top-domain statistics.</p></div><div><h2 className="mb-3 text-lg font-semibold">What the pipeline cannot establish.</h2><p className="text-sm leading-relaxed text-muted">HTTP 200 does not prove the intended content is present. Sampled 404/500 responses do not prove a worldwide outage. URL probes cannot verify authenticated account suspension or search delisting. Network results do not prove government action or illegality.</p></div><div><h2 className="mb-3 text-lg font-semibold">Legal context has boundaries.</h2><p className="text-sm leading-relaxed text-muted">Notice and order availability remain unknown because this prototype does not search for legal documents. Anuradha Bhasin’s internet-suspension context is not automatically applied to individual URL blocks; ECHR Article 10 is comparative context only. The corpus is not a complete current-law database.</p></div><div><h2 className="mb-3 text-lg font-semibold">A score for evidence completeness.</h2><p className="text-sm leading-relaxed text-muted">The confidence field represents the fraction of probes with usable HTTP observations and is zero for simulations. It is not a legal confidence measure, constitutional rating, or probability of wrongdoing.</p></div></section>
    <section className="mb-9"><p className="eyebrow mb-4">Attribution & inspiration</p><p className="text-base leading-relaxed text-slate-200">Intake design inspired by <a className="text-signal underline underline-offset-4" href="https://bribes.fyi" target="_blank" rel="noreferrer">bribes.fyi</a>, network telemetry verification inspired by <a className="text-signal underline underline-offset-4" href="https://explorer.ooni.org" target="_blank" rel="noreferrer">OONI Explorer</a>, and statutory notice transparency inspired by <a className="text-signal underline underline-offset-4" href="https://lumendatabase.org" target="_blank" rel="noreferrer">Lumen Database</a>.</p><p className="mt-3 text-xs text-muted">These are design influences, not affiliations or endorsements.</p></section>
    <div className="print-notice mb-8 flex items-start gap-3 rounded-md border border-signal/25 bg-signal/5 p-5"><ShieldCheck size={22} className="shrink-0 text-signal" /><p className="text-sm leading-relaxed">{DISCLAIMER}</p></div><Link to="/submit" className="button-primary">Contribute a lead<ArrowRight size={16} /></Link>
  </div>;
}
